/**
 * Cleans the brand logo SVGs in assets/logos and writes:
 *   src/logo/svgs.generated.ts  one string per variant, for the <Logo> component
 *   dist/logos/*.svg            the cleaned files, for <img src> use
 *
 * Cleaning crops the square 1080 canvas to the artwork, drops the fixed id,
 * and prefixes the CSS class names per variant, so several logos can sit
 * inline on one page without their <style> rules clashing.
 * Run with `bun scripts/build-logos.ts`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { logo } from "../src/tokens";

const root = join(import.meta.dir, "..");
const outDir = join(root, "dist/logos");
mkdirSync(outDir, { recursive: true });

// Measured bounds of the artwork inside every variant's 1080x1080 canvas.
const VIEWBOX = "38 177 1004 726";

const clean = (svg: string, variant: string) =>
  svg
    .replace(/<\?xml[^>]*\?>\s*/, "")
    .replace(/\s(id|data-name)="[^"]*"/g, "")
    .replace(/viewBox="[^"]*"/, `viewBox="${VIEWBOX}"`)
    .replace(/cls-(\d+)/g, `sla-logo-${variant}-$1`)
    .replace(/>\s+</g, "><")
    .replace(/\s{2,}/g, " ")
    .trim();

const entries = logo.variants.map((variant) => {
  const svg = clean(readFileSync(join(root, "assets/logos", `logo-${variant}.svg`), "utf8"), variant);
  writeFileSync(join(outDir, `logo-${variant}.svg`), svg);
  return `  "${variant}": ${JSON.stringify(svg)},`;
});

writeFileSync(
  join(root, "src/logo/svgs.generated.ts"),
  `// Generated by scripts/build-logos.ts from assets/logos. Do not edit.\nimport type { LogoVariant } from "../tokens";\n\nexport const logoSvgs: Record<LogoVariant, string> = {\n${entries.join("\n")}\n};\n\nexport const LOGO_ASPECT = ${(1004 / 726).toFixed(4)};\n`,
);
console.log(`logos: wrote ${entries.length} variants`);
